language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: setup=lowest
    - php: 7.3
      env: setup=lowest

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
